"""Reproduce the 2025 table: python3 scripts/extract-tax-table.py IRS_1040_PDF.

Requires Poppler pdftotext. Uses printed pages 68–79 of the official 2025
instructions. Rejects gaps, overlaps, duplicates and malformed row counts.
The downloaded PDF is not needed by the app, tests or normal build.
"""
import hashlib
import pathlib
import re
import subprocess
import sys

pdf = pathlib.Path(sys.argv[1])
text = subprocess.check_output(['pdftotext', '-f', '68', '-l', '79', '-raw', str(pdf), '-'], text=True)
rows = []
for line in text.splitlines():
    if re.fullmatch(r'\d[\d,]*(?: +\d[\d,]*){5}', line.strip()):
        rows.append([int(n.replace(',', '')) for n in line.split()])
rows.sort()
assert rows and rows[0] == [0, 5, 0, 0, 0, 0]
assert rows[-1] == [99950, 100000, 16909, 11823, 16909, 15170]
for i, row in enumerate(rows):
    assert row[0] < row[1] and all(n >= 0 for n in row)
    if i:
        assert rows[i-1][1] == row[0], (rows[i-1], row)
out = pathlib.Path('src/tax/2025/taxTable.ts')
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('// IRS 2025 Form 1040 instructions, pp.68–79; public-domain US government data.\n'
    '// https://www.irs.gov/pub/irs-prior/i1040gi--2025.pdf#page=68\n'
    '// Generated by scripts/extract-tax-table.py; do not hand-edit.\n'
    '// PDF SHA-256: ' + hashlib.sha256(pdf.read_bytes()).hexdigest() + '\n'
    '// Columns: lower inclusive, upper exclusive, single, MFJ/QSS, MFS, HOH.\n'
    'export const taxTable: readonly (readonly number[])[] = [\n'
    + ''.join('  [' + ','.join(map(str, row)) + '],\n' for row in rows) + '];\n')
print(f'{len(rows)} contiguous IRS table rows written to {out}')
