import type { CarryoverInput } from '../../vendor/telostax/src/engine/capitalLossCarryover';

// Manually worked expectations, never generated by the calculator under test.
// All cases below are SYNTHETIC applications of the official incoming worksheet.
// Amounts describe the 2024 return; worksheet outputs are carryovers into 2025.
export const carryoverSource = {
  url: 'https://www.irs.gov/pub/irs-prior/i1040sd--2025.pdf#page=10',
  checked: '2026-09-27',
  section: 'Capital Loss Carryover Worksheet, lines 1–13',
};

interface WorksheetFixture {
  name: string;
  input: CarryoverInput;
  // Only applicable IRS lines are asserted. The engine also emits zeros/derived
  // values on branches the paper worksheet skips; those are not IRS entries.
  lines: Record<number, number>;
  short: number;
  long: number;
}

export const worksheetFixtures: WorksheetFixture[] = [
  {
    name: 'both losses: consume short-term first, then long-term',
    input: { taxableIncomeUnfloored: 20000, shortTerm: -1000, longTerm: -6000, lossDeduction: 3000 },
    lines: { 1: 20000, 2: 3000, 3: 23000, 4: 3000, 5: 1000, 6: 0, 7: 3000, 8: 0, 9: 6000, 10: 0, 11: 2000, 12: 2000, 13: 4000 },
    short: 0, long: 4000,
  },
  {
    name: 'both losses: partial absorption leaves both characters',
    input: { taxableIncomeUnfloored: -2500, shortTerm: -1000, longTerm: -6000, lossDeduction: 3000 },
    lines: { 1: -2500, 2: 3000, 3: 500, 4: 500, 5: 1000, 6: 0, 7: 500, 8: 500, 9: 6000, 10: 0, 11: 0, 12: 0, 13: 6000 },
    short: 500, long: 6000,
  },
  {
    name: 'both losses: no income available, preserve all losses',
    input: { taxableIncomeUnfloored: -3000, shortTerm: -1000, longTerm: -6000, lossDeduction: 3000 },
    lines: { 1: -3000, 2: 3000, 3: 0, 4: 0, 5: 1000, 6: 0, 7: 0, 8: 1000, 9: 6000, 10: 0, 11: 0, 12: 0, 13: 6000 },
    short: 1000, long: 6000,
  },
  {
    name: 'short loss offsets long gain even with partial income absorption',
    input: { taxableIncomeUnfloored: -2500, shortTerm: -7000, longTerm: 2000, lossDeduction: 3000 },
    lines: { 1: -2500, 2: 3000, 3: 500, 4: 500, 5: 7000, 6: 2000, 7: 2500, 8: 4500 },
    short: 4500, long: 0,
  },
  {
    name: 'long loss offsets short gain even with partial income absorption',
    input: { taxableIncomeUnfloored: -2500, shortTerm: 2000, longTerm: -7000, lossDeduction: 3000 },
    lines: { 1: -2500, 2: 3000, 3: 500, 4: 500, 5: 0, 9: 7000, 10: 2000, 11: 500, 12: 2500, 13: 4500 },
    short: 0, long: 4500,
  },
  {
    name: 'loss below annual cap still carries when income absorbs none',
    input: { taxableIncomeUnfloored: -2500, shortTerm: -2000, longTerm: 0, lossDeduction: 2000 },
    lines: { 1: -2500, 2: 2000, 3: 0, 4: 0, 5: 2000, 6: 0, 7: 0, 8: 2000 },
    short: 2000, long: 0,
  },
  {
    name: 'loss below annual cap carries only its unabsorbed part',
    input: { taxableIncomeUnfloored: -500, shortTerm: 0, longTerm: -2000, lossDeduction: 2000 },
    lines: { 1: -500, 2: 2000, 3: 1500, 4: 1500, 5: 0, 9: 2000, 10: 0, 11: 1500, 12: 1500, 13: 500 },
    short: 0, long: 500,
  },
  {
    name: 'small loss fully absorbed at exactly zero taxable income',
    input: { taxableIncomeUnfloored: 0, shortTerm: -2000, longTerm: 0, lossDeduction: 2000 },
    lines: { 1: 0, 2: 2000, 3: 2000, 4: 2000, 5: 2000, 6: 0, 7: 2000, 8: 0 },
    short: 0, long: 0,
  },
  {
    name: '2024 MFS cap: allocate deduction across both loss characters',
    input: { taxableIncomeUnfloored: 10000, shortTerm: -1000, longTerm: -4000, lossDeduction: 1500 },
    lines: { 1: 10000, 2: 1500, 3: 11500, 4: 1500, 5: 1000, 6: 0, 7: 1500, 8: 0, 9: 4000, 10: 0, 11: 500, 12: 500, 13: 3500 },
    short: 0, long: 3500,
  },
  {
    name: '2024 MFS cap: partial absorption of a long-term loss',
    input: { taxableIncomeUnfloored: -1000, shortTerm: 0, longTerm: -5000, lossDeduction: 1500 },
    lines: { 1: -1000, 2: 1500, 3: 500, 4: 500, 5: 0, 9: 5000, 10: 0, 11: 500, 12: 500, 13: 4500 },
    short: 0, long: 4500,
  },
  {
    name: 'one cent of income consumes one cent of short loss',
    input: { taxableIncomeUnfloored: -2999.99, shortTerm: -1000, longTerm: -4000, lossDeduction: 3000 },
    lines: { 1: -2999.99, 2: 3000, 3: 0.01, 4: 0.01, 5: 1000, 6: 0, 7: 0.01, 8: 999.99, 9: 4000, 10: 0, 11: 0, 12: 0, 13: 4000 },
    short: 999.99, long: 4000,
  },
];
